curr=float(input("The currency:"))
print(curr)
print("1.",curr,'ruppes',"(Indian)")
print("2.",curr/71.95,'dollar',"(United state)")
print("3.",curr/10.12,'yuan',"(China)")
print("4.",curr/0.85,'taca',"(Bangladesh)")
print("5.",curr/0.67,'yen',"(Japan)")
print("6.",curr/1.10,'ruble',"(Russia)")
print("7.",curr/0.40,'srilankanrupees',"(Srilanka)")
print("8.",curr/51.99,'singapordollar',"(Singapor)")
#only for Indian Rupees
